spring:
  application:
    name: iqmei-api-gateway-service
  zipkin:
    base-url:  http://localhost:10000/
  sleuth:
    sampler:
      probability: 1  
            
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
            
server:
  port: 3000

  
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true  
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:4010/eureka}
  instance:
    preferIpAddress: true
                                              

zuul:
  prefix: /api/v1
  ignoredServices: "*"
  sslHostnameValidationEnabled: false
  routes:
    iqmei-db-engine:
      path: /db/**
      #url: http://localhost:5000
      serviceId: iqmei-db-engine
      sensitiveHeaders:
      
    iqmei-itch-service:
      path: /itch/**
      #url: http://localhost:5001
      serviceId: iqmei-itch-service
      sensitiveHeaders:      
      
    iqmei-fix-service:
      path: /fix/**
      #url: http://localhost:5002
      serviceId: iqmei-fix-service
      sensitiveHeaders:
     
    iqmei-core-service:
      path: /core/**
      #url: http://localhost:7000
      serviceId: iqmei-core-service
      sensitiveHeaders:        
      
    iqmei-auth-service:
      path: /auth/**
      #url: http://localhost:3500
      serviceId: iqmei-auth-service
      sensitiveHeaders:
      
    iqmei-service-registry-server:
      path: /discovery/**
      #url: http://localhost:4000
      serviceId: iqmei-service-registry-server
      sensitiveHeaders: 
      
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: false

    hystrix:
      config:
        command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
        
  endpoints:
    web:
      exposure:
        include: "*"      
        
#ribbon.ConnectTimeout: 50000
#ribbon.ReadTimeout: 50000
  
ribbon.restclient.enabled: true  
 
zuul.host.connectTimeoutMillis: 600000
zuul.host.socketTimeoutMillis: 600000
zuul.retryable: true

#30 seconds timeout
ribbon:
  ReadTimeout: 30000
  ribbon.ConnectTimeout: 30000
  maxAutoRetries: 30
  MaxAutoRetriesNextServer: 30
  OkToRetryOnAllOperations: true
  
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000

#=============MULTIPART CONFIGURATION==================#
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: -1
spring.servlet.multipart.max-request-size: -1

#=============JWT CONFIGURATION==================#
security.jwt.expiration: 18000
security.jwt.secret: XY7kmzoNzl100
#=============global constant ================
globalconstant:
  another_device_err: This account is already logged in on another device.
  default_secret_key: 25f9e794323b453885f5181f1b624d0b		
  single_user_filter_status: true		
  #single_user_filter_status: false
#=============global constant ================
#==for send mail error two time call====
feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000
#==for send mail error two time call====
#===============Enable/disable swagger ui comment bottom line in production ====
#swagger.apiDocPostfix: v2/api-docs
#swagger.apiDocPostfix: 
#===============Enable/disable swagger ui comment bottom line in production ====
#===============swagger ui comment bottom line in production ====
swaggerconstant:
  apiDocPostfix: v2/api-docs #Enable/disable
  #apiDocPostfix: 
  base_package: com.hiteshi.iqmei.api.gateway.service
  project_title: IQMEI Api
  project_description: IQMEI Api for IQMEI Web and Mobile Client(s) 
  version: 1.0.0-v2
  company_name: Hiteshi Infotech
  company_url: http://www.iqmei.com
  company_email: marcos.sicat@iqmei.com
  company_license: Apache 2.0
  company_license_url: http://www.apache.org/licenses/LICENSE-2.0
#===============Enable/disable swagger ui comment bottom line in production ====