
spring:
  application:
    name: iqmei-core-service
  zipkin:
    base-url:  http://localhost:10000/
  sleuth:
    sampler:
      probability: 1  
            
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
    
server:
  port: 7000

#-Dspring.profiles.active: iqmei-core-engine-dev


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://reg.atlasifs.com:4000/eureka}
  instance:
    preferIpAddress: true

#spring:
  #profiles:
    #include:
      #- iqmei-common-server


#==================GOOGLE STORAGE CONFIGURATION =================
spring.cloud.gcp.credentials.location: classpath:google_auth.json

global:
  core:
    google:
      cloud:
        storage:
          config:
            file: google_auth.json
          bucket_name: iqmei-users-data-storage
          image_dir: users-profile-images/
          meta_registration: meta.registration.json
          pre_meta_registration: users-profile-images/file-2019-02-25-065623524

#==================MULTIPART FILE =================
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: -1
spring.servlet.multipart.max-request-size: -1
#email_bharat: bharat.chandel@hiteshi.com

#==================FCM CONFIGURATION =================
#Android
#fcm.server_key: AAAAmnW5Ci8:APA91bEmZGMF45zFXL6Zkb7kEk39YwxbZUhmgsrJ5wTOTu6e52VYKjxdRmnDVz6_afYgy5gjlDDyOPteo0-14stW_gxlEaXKNgwLkrlMBcB8u7trpSGtTSUhcgZ_9D9iyZZUfEA8PUYL
fcm.server_key: AAAAMUKZZ9Q:APA91bEbW_E4a03DGwLY5vaGbL0GsQnCCGH8-C_09-XEgUXiuzs6LER7MKlii4aHJq2uZzc5OXotHOr8UDwdrU-EOAuNM78yMTJO2K0byAehvZdLwO0zPdM46cuWaXGjDVffT4AnR7C7
#fcm.server_key: AAAAMUKZZ9Q:APA91bFZkt6-oogN9ihKTSTYGjT0G0pDsCnQe6wmJeIAw4yfRDVjTREZubzhLWAOmhclWz3QNBwkKNqtLJ0fEsnyeRcO2qrsvvNOgvTMzFp3lqesU3rgX2Pmo8_fL9iMW6kOTahuGqON
#==================CONSTATANT CONFIGURATION =================
globalconstant:
  method_error: Method error occurred and error is 
  method_success: Method successfully called in 
  success_status: false
  error_status: true 
  already_exist: Already exist please try another  
  record_list: List of records 
  record_delete: Record has been removed!
  record_added: Record has been added
  record_updated: Record has been updated
  record_details: Record details
  not_exist: Record has been not found!
  some_thing_wrong: Something went wrong please try again
  requiredParameters: Parameter {0} is required!.
  file_uploaded: File has been successfully uploaded
  inavalid_image: File must be an image
#==================CONSTATANT CONFIGURATION =================
#==for send mail error two time call====
feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000
#==for send mail error two time call====
#===============swagger ui comment bottom line in production ====
swaggerconstant:
  base_package: com.hiteshi.iqmei.core.service
  project_title: IQMEI Api
  project_description: IQMEI Api for IQMEI Web and Mobile Client(s) 
  version: 1.0.0-v2
  company_name: Hiteshi Infotech
  company_url: http://www.hiteshi.com
  company_email: support@hiteshi.com
  company_license: Apache 2.0
  company_license_url: http://www.apache.org/licenses/LICENSE-2.0
#===============Enable/disable swagger ui comment bottom line in production ====